### ISSUE TITLE
Formatting check on the appendix

### ISSUE THREAD

**Issue by Pzoom522** [yz-joey/ACLPUB#2]
Thanks for this great tool! However, I found that it will also check the formats of pages after the references (i.e., appendix), which I believe is unnecessary.

**Comment by bethard** [comment]
Checks on pages in the appendix are definitely intentional; appendices should follow the same format as the rest of the paper. This is especially true for page size and margin checks, though it's probably true for many of the other checks too. Is there a specific check that you thought was inappropriate for the appendix?

**Comment by Pzoom522** [comment]
Many thanks for the classification, I see your points now. Closing this solved issue.
